# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal9830-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter r8s x1s x1slte z3s,$(TARGET_DEVICE)),)

endif
